# -----------------------------------------------------------------------------
# Docker Compose for the ResearchAgent
#
# MODIFICATION FOR OLLAMA:
# Added the `extra_hosts` section. This is the standard way to allow a
# Docker container to communicate with services running on the host machine
# (like a local Ollama server). It maps the special hostname
# `host.docker.internal` to the host's gateway IP address.
# -----------------------------------------------------------------------------

services:
  # Defines our backend service.
  backend:
    # Tells Compose to build the image from the Dockerfile in the current directory.
    build: .

    # Loads environment variables from the .env file in the project root.
    env_file:
      - .env

    # Maps ports from the host machine to the container.
    ports:
      - "8765:8765"
      - "8766:8766"

    # --- NEW: Added for Ollama connection ---
    # This makes the host machine accessible from inside the container
    # via the hostname 'host.docker.internal'.
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # Mounts local directories (volumes) into the container.
    # This allows for live code updates and persistent storage.
    volumes:
      - ./backend:/app/backend
      - ./workspace:/app/workspace

    # Keeps stdin open, which is useful for interactive debugging if needed.
    stdin_open: true

