# -----------------------------------------------------------------------------
# Docker Compose for Mentor::i
#
# MODIFICATION FOR DATA PERSISTENCE:
# Added a new volume mapping: `./data:/app/data`. This creates a `data`
# directory in your project folder and makes it available inside the
# container. This is where the application's main SQLite database will be
# stored, separating it from the agent's temporary workspace files.
# -----------------------------------------------------------------------------

services:
  # Defines our backend service.
  backend:
    # Tells Compose to build the image from the Dockerfile in the current directory.
    build: .

    # Loads environment variables from the .env file in the project root.
    env_file:
      - .env

    # Maps ports from the host machine to the container.
    ports:
      - "8765:8765"
      - "8766:8766"

    # Makes the host machine accessible from inside the container.
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # Mounts local directories (volumes) into the container.
    volumes:
      - ./backend:/app/backend
      - ./workspace:/app/workspace
      # --- NEW: Add a dedicated volume for persistent application data ---
      - ./data:/app/data

    # Keeps stdin open, which is useful for interactive debugging if needed.
    stdin_open: true
