version: '3.8'

services:
  backend:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: research_agent_backend
    ports:
      - "8765:8765" # Map host port 8765 to container port 8765 (WebSocket)
      - "8766:8766" # Map host port 8766 to container port 8766 (File Server)
    volumes:
      # Mount local code into the container for development
      # Changes in local ./backend reflect inside the container at /app/backend
      - ./backend:/app/backend
      # Mount local workspace into the container's workspace
      # Files created by the agent persist locally
      - ./workspace:/app/workspace
      # Mount local database directory into the container
      # Database file persists locally
      - ./database:/app/database
      # Mount the local .env file into the container
      # Provides API keys and configuration to the running app
      - ./.env:/app/.env
    # Ensure the container restarts automatically if it crashes (optional)
    restart: unless-stopped
    # Use the .env file in the project root for environment variables within the container
    env_file:
      - .env