# -----------------------------------------------------------------------------
# Docker Compose for the ResearchAgent
#
# This file defines and configures the services for our application,
# making it easy to run the entire backend with a single command:
# `docker compose up --build`
# -----------------------------------------------------------------------------

services:
  # Defines our backend service.
  backend:
    # Tells Compose to build the image from the Dockerfile in the current directory.
    build: .

    # Loads environment variables from the .env file in the project root.
    env_file:
      - .env

    # Maps ports from the host machine to the container.
    ports:
      - "8765:8765"
      - "8766:8766"

    # Mounts local directories (volumes) into the container.
    # This allows for live code updates and persistent storage.
    volumes:
      - ./backend:/app/backend
      - ./workspace:/app/workspace

    # Keeps stdin open, which is useful for interactive debugging if needed.
    stdin_open: true
    # Allocates a pseudo-TTY.
    tty: true
