#!/usr/bin/env python3
"""
Paper Processing Pipeline for V4 Experiments.

Uses Gemini (default: gemini-2.5-flash-preview) to:
1. Analyze paper content (methods, findings, figures, tables)
2. Generate draft evaluation questions
3. Export review spreadsheet for human validation

Gemini API key is fetched automatically from the Mentori admin account
stored in the local SQLite database. Falls back to the GEMINI_API_KEY
environment variable if no key is found in the DB.

Usage:
    # Process single paper
    uv run python publication/scripts/paper_processor.py process paper.pdf

    # Process all papers in directory (default: datasets/v4_papers/core/)
    uv run python publication/scripts/paper_processor.py process-all

    # Process a specific directory
    uv run python publication/scripts/paper_processor.py process-all --dir datasets/core_papers/

    # Generate questions from processed papers
    uv run python publication/scripts/paper_processor.py generate-questions

    # Export review spreadsheet
    uv run python publication/scripts/paper_processor.py export-review

    # Import reviewed spreadsheet
    uv run python publication/scripts/paper_processor.py import-review reviewed_questions.csv

    # Use a different Gemini model
    uv run python publication/scripts/paper_processor.py process-all --model gemini-2.0-flash
"""

import argparse
import asyncio
import csv
import json
import logging
import os
import sys
from dataclasses import dataclass, asdict, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("paper_processor")

# Default Gemini model — override with --model flag
DEFAULT_MODEL = "gemini-3-flash-preview"

# Directories
DATASETS_DIR = PROJECT_ROOT / "datasets"
V4_PAPERS_DIR = DATASETS_DIR / "v4_papers" / "core"
METADATA_DIR = DATASETS_DIR / "paper_metadata"
QUESTIONS_DRAFT_DIR = DATASETS_DIR / "questions_draft"
QUESTIONS_DIR = DATASETS_DIR / "questions"


def _get_gemini_api_key() -> str:
    """Fetch the Gemini API key from the Mentori admin DB, falling back to env var.

    Priority:
    1. Admin user settings in SQLite DB (admin@mentori or admin@wur.nl)
    2. GEMINI_API_KEY environment variable
    """
    try:
        from backend.database import engine
        from backend.models.user import User
        from sqlmodel import Session, select

        admin_emails = ["admin@mentori", "admin@wur.nl"]
        with Session(engine) as session:
            for email in admin_emails:
                user = session.exec(select(User).where(User.email == email)).first()
                if user:
                    api_keys = (user.settings or {}).get("api_keys", {})
                    key = api_keys.get("gemini") or api_keys.get("GEMINI_API_KEY")
                    if key:
                        logger.info(f"Loaded Gemini API key from admin account ({email})")
                        return key
    except Exception as e:
        logger.debug(f"Could not load key from DB: {e}")

    # Fallback to environment variable
    key = os.environ.get("GEMINI_API_KEY", "")
    if key:
        logger.info("Loaded Gemini API key from GEMINI_API_KEY environment variable")
        return key

    raise ValueError(
        "Gemini API key not found.\n"
        "  Option 1: Add your key in Mentori Settings → API Keys (recommended)\n"
        "  Option 2: export GEMINI_API_KEY='your-key'"
    )


@dataclass
class ContentAnalysis:
    """Extracted content from paper analysis."""
    research_question: str = ""
    methods: List[str] = field(default_factory=list)
    findings: List[Dict[str, Any]] = field(default_factory=list)
    figures: List[Dict[str, Any]] = field(default_factory=list)
    tables: List[Dict[str, Any]] = field(default_factory=list)
    technical_terms: List[str] = field(default_factory=list)
    limitations: List[str] = field(default_factory=list)
    connections: List[str] = field(default_factory=list)


@dataclass
class DraftQuestion:
    """A draft question generated by Gemini."""
    q_id: str
    paper_id: str
    question: str
    category: str  # factual_recall, conceptual, technical
    expected_answer: str
    expected_concepts: List[str]
    difficulty: str  # easy, medium, hard
    source_page: str
    requires_iteration: bool
    status: str = "pending"  # pending, accept, modify, reject
    reviewer_notes: str = ""
    corrected_answer: str = ""


# Gemini prompts
CONTENT_ANALYSIS_PROMPT = """You are analyzing a scientific paper to extract structured information.

Paper filename: {filename}
Available metadata: {metadata}

Analyze the full paper and extract:

1. **Main Research Question**: What problem does this paper address?
2. **Key Methods**: What techniques, algorithms, or approaches are used?
3. **Key Findings**: What are the main results (with specific numbers if available)?
4. **Figures Summary**: List each figure with a one-sentence description
5. **Tables Summary**: List each table with column names and purpose
6. **Technical Terms**: List domain-specific terms defined or heavily used
7. **Limitations**: What limitations do the authors acknowledge?
8. **Connections**: What other papers/methods does this build upon?

Return as JSON:
{{
  "research_question": "...",
  "methods": ["method1", "method2"],
  "findings": [{{"finding": "...", "evidence": "...", "page": N}}],
  "figures": [{{"id": "Figure 1", "description": "...", "page": N}}],
  "tables": [{{"id": "Table 1", "description": "...", "columns": [...]}}],
  "technical_terms": ["term1", "term2"],
  "limitations": ["..."],
  "connections": ["paper/method referenced"]
}}
"""

QUESTION_GENERATION_PROMPT = """You are creating evaluation questions for a scientific RAG system.

Paper: {title}
Authors: {authors}
Abstract: {abstract}
Methods: {methods}
Findings: {findings}
Figures: {figures}
Tables: {tables}

Generate exactly 3 questions for this paper:

1. **FACTUAL RECALL**: A question with a specific, extractable answer.
   - Should test retrieval of explicit facts (names, dates, numbers, definitions)
   - Answer should be directly quotable from the paper

2. **CONCEPTUAL**: A question requiring understanding, not just retrieval.
   - Should test comprehension of ideas, relationships, or reasoning
   - Answer requires synthesizing information from multiple parts of the paper

3. **TECHNICAL**: A question about methods, tools, or specific metrics.
   - Should require understanding of procedures or numerical results
   - Often involves specific numbers, parameters, or step-by-step processes

For each question, provide:
- question: The question text (clear, specific, ends with ?)
- category: "factual_recall" | "conceptual" | "technical"
- expected_answer: A complete answer (2-4 sentences)
- expected_concepts: List of 3-6 key terms that should appear in a correct answer
- difficulty: "easy" | "medium" | "hard"
- source_page: Page number(s) where the answer can be found
- requires_iteration: true if answer requires combining info from multiple sections

Return as JSON array of 3 question objects:
[
  {{
    "question": "...",
    "category": "factual_recall",
    "expected_answer": "...",
    "expected_concepts": ["...", "..."],
    "difficulty": "easy",
    "source_page": "1-2",
    "requires_iteration": false
  }},
  ...
]
"""


class PaperProcessor:
    """Process papers using Gemini for content analysis and question generation."""

    def __init__(self, model: str = DEFAULT_MODEL, api_key: Optional[str] = None):
        """Initialize with optional Gemini model and API key.

        Args:
            model: Gemini model identifier (default: gemini-2.5-flash-preview)
            api_key: Override API key. If not provided, fetched from Mentori DB or env var.
        """
        self.api_key = api_key or _get_gemini_api_key()

        try:
            from google import genai as genai_sdk
            self.client = genai_sdk.Client(api_key=self.api_key)
            self.model_name = model
            logger.info(f"Initialized Gemini model: {model}")
        except ImportError:
            raise ImportError(
                "google-genai not installed. Run: uv add google-genai"
            )

    async def process_paper(self, pdf_path: Path) -> Dict[str, Any]:
        """Full pipeline: metadata → content analysis → question generation."""
        paper_id = pdf_path.stem
        logger.info(f"Processing paper: {paper_id}")

        # 1. Load external metadata if available
        metadata = self._load_metadata(paper_id)

        # 2. Analyze content with Gemini
        content = await self._analyze_content(pdf_path, metadata)

        # 3. Generate draft questions
        questions = await self._generate_questions(paper_id, metadata, content)

        result = {
            "paper_id": paper_id,
            "filename": pdf_path.name,
            "metadata": metadata,
            "content_analysis": asdict(content) if isinstance(content, ContentAnalysis) else content,
            "draft_questions": [asdict(q) if isinstance(q, DraftQuestion) else q for q in questions],
            "status": "pending_review",
            "processed_at": datetime.now().isoformat(),
        }

        # Save draft
        QUESTIONS_DRAFT_DIR.mkdir(parents=True, exist_ok=True)
        draft_file = QUESTIONS_DRAFT_DIR / f"{paper_id}_draft.json"
        with open(draft_file, "w") as f:
            json.dump(result, f, indent=2)

        logger.info(f"Saved draft to {draft_file}")
        return result

    def _load_metadata(self, paper_id: str) -> Dict[str, Any]:
        """Load metadata from metadata_fetcher output."""
        meta_file = METADATA_DIR / f"{paper_id}_meta.json"
        if meta_file.exists():
            with open(meta_file) as f:
                return json.load(f)
        return {}

    async def _analyze_content(
        self,
        pdf_path: Path,
        metadata: Dict[str, Any],
    ) -> ContentAnalysis:
        """Send PDF to Gemini for content extraction."""
        try:
            # Upload PDF to Gemini
            pdf_file = self.client.files.upload(file=str(pdf_path))

            prompt = CONTENT_ANALYSIS_PROMPT.format(
                filename=pdf_path.name,
                metadata=json.dumps(metadata, indent=2) if metadata else "None available",
            )

            response = self.client.models.generate_content(
                model=self.model_name,
                contents=[pdf_file, prompt],
            )
            text = response.text

            # Parse JSON from response
            json_start = text.find("{")
            json_end = text.rfind("}") + 1
            if json_start >= 0 and json_end > json_start:
                data = json.loads(text[json_start:json_end])
                return ContentAnalysis(**data)

        except Exception as e:
            logger.error(f"Content analysis failed: {e}")

        return ContentAnalysis()

    async def _generate_questions(
        self,
        paper_id: str,
        metadata: Dict[str, Any],
        content: ContentAnalysis,
    ) -> List[DraftQuestion]:
        """Generate 3 draft questions per paper."""
        try:
            prompt = QUESTION_GENERATION_PROMPT.format(
                title=metadata.get("title", "Unknown"),
                authors=", ".join(metadata.get("authors", [])),
                abstract=metadata.get("abstract", "Not available"),
                methods=", ".join(content.methods) if content.methods else "Not extracted",
                findings=json.dumps(content.findings) if content.findings else "Not extracted",
                figures=json.dumps(content.figures) if content.figures else "None",
                tables=json.dumps(content.tables) if content.tables else "None",
            )

            response = self.client.models.generate_content(
                model=self.model_name,
                contents=prompt,
            )
            text = response.text

            # Parse JSON array from response
            json_start = text.find("[")
            json_end = text.rfind("]") + 1
            if json_start >= 0 and json_end > json_start:
                questions_data = json.loads(text[json_start:json_end])

                questions = []
                for i, q in enumerate(questions_data):
                    cat_abbrev = {"factual_recall": "FR", "conceptual": "CO", "technical": "TE"}
                    q_id = f"{paper_id}_{cat_abbrev.get(q.get('category', 'FR'), 'Q')}{i+1}"

                    questions.append(DraftQuestion(
                        q_id=q_id,
                        paper_id=paper_id,
                        question=q.get("question", ""),
                        category=q.get("category", "unknown"),
                        expected_answer=q.get("expected_answer", ""),
                        expected_concepts=q.get("expected_concepts", []),
                        difficulty=q.get("difficulty", "medium"),
                        source_page=str(q.get("source_page", "")),
                        requires_iteration=q.get("requires_iteration", False),
                    ))

                return questions

        except Exception as e:
            logger.error(f"Question generation failed: {e}")

        return []


async def process_single(pdf_path: Path, model: str = DEFAULT_MODEL) -> Dict[str, Any]:
    """Process a single paper."""
    processor = PaperProcessor(model=model)
    return await processor.process_paper(pdf_path)


async def process_all(directory: Path, model: str = DEFAULT_MODEL) -> List[Dict[str, Any]]:
    """Process all papers in a directory, one at a time (sequential with rate limiting).

    Algorithm per paper:
      1. Load external metadata from paper_metadata/ if available
      2. Upload PDF to Gemini Files API
      3. Content analysis: extract research question, methods, findings, figures, tables
      4. Question generation: produce 3 draft questions (factual, conceptual, technical)
      5. Save draft JSON to questions_draft/
    """
    # Skip already-processed papers
    already_done = {f.stem.replace("_draft", "") for f in QUESTIONS_DRAFT_DIR.glob("*_draft.json")}

    pdf_files = sorted(directory.rglob("*.pdf"))
    pending = [p for p in pdf_files if p.stem not in already_done]

    logger.info(f"Found {len(pdf_files)} PDFs | {len(already_done)} already processed | {len(pending)} to process")

    processor = PaperProcessor(model=model)
    results = []

    for i, pdf_path in enumerate(pending):
        logger.info(f"[{i+1}/{len(pending)}] Processing {pdf_path.name}")
        try:
            result = await processor.process_paper(pdf_path)
            results.append(result)
            # Rate limiting for Gemini API
            await asyncio.sleep(2)
        except Exception as e:
            logger.error(f"Failed to process {pdf_path.name}: {e}")

    return results


def export_review_spreadsheet() -> Path:
    """Export draft questions to review spreadsheet."""
    if not QUESTIONS_DRAFT_DIR.exists():
        raise FileNotFoundError(f"No draft questions found in {QUESTIONS_DRAFT_DIR}")

    all_questions = []
    for draft_file in QUESTIONS_DRAFT_DIR.glob("*_draft.json"):
        with open(draft_file) as f:
            data = json.load(f)

        paper_title = data.get("metadata", {}).get("title", data["paper_id"])

        for q in data.get("draft_questions", []):
            all_questions.append({
                "paper_id": data["paper_id"],
                "paper_title": paper_title,
                "q_id": q["q_id"],
                "q_type": q["category"],
                "question": q["question"],
                "expected_answer": q["expected_answer"],
                "expected_concepts": ", ".join(q.get("expected_concepts", [])),
                "difficulty": q["difficulty"],
                "source_page": q.get("source_page", ""),
                "status": "PENDING",
                "reviewer_notes": "",
                "corrected_answer": "",
                "corrected_concepts": "",
            })

    # Export to CSV
    output_file = DATASETS_DIR / "review_spreadsheet.csv"
    with open(output_file, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=all_questions[0].keys())
        writer.writeheader()
        writer.writerows(all_questions)

    logger.info(f"Exported {len(all_questions)} questions to {output_file}")
    return output_file


def import_reviewed_spreadsheet(csv_path: Path) -> None:
    """Import reviewed spreadsheet and update question files."""
    with open(csv_path, newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    # Group by paper_id
    by_paper = {}
    for row in rows:
        paper_id = row["paper_id"]
        if paper_id not in by_paper:
            by_paper[paper_id] = []
        by_paper[paper_id].append(row)

    # Update draft files
    for paper_id, questions in by_paper.items():
        draft_file = QUESTIONS_DRAFT_DIR / f"{paper_id}_draft.json"
        if not draft_file.exists():
            logger.warning(f"Draft file not found: {draft_file}")
            continue

        with open(draft_file) as f:
            data = json.load(f)

        # Update questions
        for q in data.get("draft_questions", []):
            matching = [r for r in questions if r["q_id"] == q["q_id"]]
            if matching:
                row = matching[0]
                q["status"] = row["status"].lower()
                q["reviewer_notes"] = row["reviewer_notes"]
                if row["corrected_answer"]:
                    q["expected_answer"] = row["corrected_answer"]
                if row["corrected_concepts"]:
                    q["expected_concepts"] = [c.strip() for c in row["corrected_concepts"].split(",")]

        with open(draft_file, "w") as f:
            json.dump(data, f, indent=2)

    logger.info(f"Updated {len(by_paper)} paper draft files")

    # Generate final ground truth from accepted questions
    _generate_ground_truth()


def _generate_ground_truth() -> None:
    """Generate final ground truth from accepted questions."""
    accepted = []

    for draft_file in QUESTIONS_DRAFT_DIR.glob("*_draft.json"):
        with open(draft_file) as f:
            data = json.load(f)

        for q in data.get("draft_questions", []):
            if q.get("status") in ["accept", "modify"]:
                accepted.append({
                    "id": q["q_id"],
                    "question": q["question"],
                    "category": q["category"],
                    "answerable": True,
                    "source_files": [data["filename"]],
                    "expected_answer": q["expected_answer"],
                    "expected_concepts": q["expected_concepts"],
                    "difficulty": q["difficulty"],
                    "requires_iteration": q.get("requires_iteration", False),
                    "min_core": 5,  # Default, will be updated based on paper assignment
                })

    QUESTIONS_DIR.mkdir(parents=True, exist_ok=True)
    output_file = QUESTIONS_DIR / "paper_level.json"
    with open(output_file, "w") as f:
        json.dump({"questions": accepted}, f, indent=2)

    logger.info(f"Generated {len(accepted)} accepted questions to {output_file}")


def main():
    parser = argparse.ArgumentParser(description="Process papers and generate questions")
    parser.add_argument(
        "--model",
        default=DEFAULT_MODEL,
        help=f"Gemini model to use (default: {DEFAULT_MODEL})",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # process command
    process_parser = subparsers.add_parser("process", help="Process a single paper")
    process_parser.add_argument("pdf_path", type=Path, help="Path to PDF file")

    # process-all command
    process_all_parser = subparsers.add_parser(
        "process-all",
        help=f"Process all papers in a directory (default: {V4_PAPERS_DIR})",
    )
    process_all_parser.add_argument(
        "--dir",
        type=Path,
        default=V4_PAPERS_DIR,
        help="Directory containing PDFs (default: datasets/v4_papers/core/)",
    )

    # generate-questions command (alias for process-all)
    subparsers.add_parser("generate-questions", help="Alias for process-all on the default core dir")

    # export-review command
    subparsers.add_parser("export-review", help="Export review spreadsheet")

    # import-review command
    import_parser = subparsers.add_parser("import-review", help="Import reviewed spreadsheet")
    import_parser.add_argument("csv_path", type=Path, help="Path to reviewed CSV")

    args = parser.parse_args()

    if args.command == "process":
        result = asyncio.run(process_single(args.pdf_path, model=args.model))
        print(f"Processed {result['paper_id']}: {len(result['draft_questions'])} questions generated")

    elif args.command == "process-all":
        results = asyncio.run(process_all(args.dir, model=args.model))
        total_questions = sum(len(r.get("draft_questions", [])) for r in results)
        print(f"\nProcessed {len(results)} papers, generated {total_questions} draft questions")
        print(f"Drafts saved to {QUESTIONS_DRAFT_DIR}")

    elif args.command == "generate-questions":
        results = asyncio.run(process_all(V4_PAPERS_DIR, model=args.model))
        total_questions = sum(len(r.get("draft_questions", [])) for r in results)
        print(f"\nGenerated {total_questions} draft questions from {len(results)} papers")

    elif args.command == "export-review":
        output = export_review_spreadsheet()
        print(f"Review spreadsheet exported to {output}")

    elif args.command == "import-review":
        import_reviewed_spreadsheet(args.csv_path)
        print("Review imported and ground truth updated")


if __name__ == "__main__":
    main()
