# backend/agents/notebook/supervisor.py
"""
Coder Supervisor for quality evaluation of code cells.

The CoderSupervisor evaluates each cell after execution to:
1. Assess correctness - does the output match expectations?
2. Assess completeness - did the cell do everything it should?
3. Assess data quality - are the results sensible?
4. Vision validation - analyze generated plots for quality
5. Trigger retries for poor-quality outputs
"""

import json
import re
import base64
from typing import Optional, Dict, Any, List, Tuple

from backend.agents.model_router import ModelRouter
from backend.agents.notebook.schema import (
    Cell,
    CellOutput,
    SupervisorEvaluation,
    Algorithm,
    AlgorithmStep,
)
from backend.agents.session_context import get_logger

logger = get_logger(__name__)


# Vision validation prompt for plot analysis
VISION_PLOT_PROMPT = """Analyze this plot generated by a data science notebook.

Evaluate the following:
1. **Data Presence**: Does the plot show actual data, or is it empty/blank?
2. **Axes Labels**: Are the X and Y axes labeled appropriately?
3. **Title**: Does the plot have a descriptive title?
4. **Legend**: If there are multiple series, is there a readable legend?
5. **Readability**: Is the text readable (not overlapping, not truncated)?
6. **Visual Quality**: Are colors distinguishable? Is the plot type appropriate?

Respond with JSON only:

```json
{
  "has_data": true,
  "axes_labeled": true,
  "has_title": true,
  "legend_readable": true,
  "text_readable": true,
  "visual_quality": "good",
  "issues": [],
  "quality_score": 85,
  "summary": "Brief summary of the plot quality"
}
```

If the image is empty, blank, or shows no data, set has_data to false and quality_score to 0.
"""


SUPERVISOR_SYSTEM_PROMPT = """You are a code quality supervisor. Your job is to evaluate code cell outputs and determine if they are correct and complete.

## Your Task

Evaluate the code cell based on:

1. **Correctness**: Does the output match what the code intended?
   - No errors or exceptions
   - Output is valid (not empty DataFrames, not NaN values, etc.)
   - Logic appears correct

2. **Completeness**: Did the cell accomplish its goal?
   - All requested operations completed
   - Output contains expected information

3. **Data Quality**: Are the results sensible?
   - Values in expected ranges
   - No unexpected null/empty values
   - Shapes and sizes make sense

4. **Plot Quality** (if applicable):
   - Plot is not empty
   - Axes are labeled appropriately
   - Data is visible

## Scoring

Assign a score from 0-100:
- 90-100: Excellent - no issues
- 70-89: Good - minor issues but acceptable
- 50-69: Acceptable - some issues but usable
- 30-49: Poor - significant issues, should retry
- 0-29: Failed - major errors, must retry

- 0-29: Failed - major errors, must retry

## IMPORTANT NOTES
- For **Import/Setup** cells, "No output" is expected and valid. Score these high (90-100) if the code is valid.
- Do not penalize for "Completeness" if the cell is clearly just one step of a larger task (e.g. just generating data).
- Only fail a cell if it has Error output or logic is clearly wrong.

## Output Format

You MUST respond with valid JSON in this exact format:

```json
{
  "score": 85,
  "is_acceptable": true,
  "correctness": "Output matches expected behavior...",
  "completeness": "All requested operations completed...",
  "data_quality": "Values appear sensible...",
  "issues": ["Minor issue 1", "Minor issue 2"],
  "suggestions": ["Consider adding..."],
  "should_retry": false,
  "has_plot": false,
  "plot_assessment": null
}
```

Respond ONLY with the JSON, no additional text.
"""


def build_evaluation_prompt(
    cell: Cell,
    algorithm_step: Optional[AlgorithmStep] = None,
    context: Optional[str] = None
) -> str:
    """Build the user prompt for cell evaluation."""
    parts = []

    # Cell source
    parts.append(f"## Code Cell\n\n```python\n{cell.source}\n```")

    # Cell output
    output_text = cell.get_output_text(max_length=2000)
    if output_text:
        parts.append(f"\n\n## Output\n\n```\n{output_text}\n```")
    else:
        parts.append("\n\n## Output\n\n(No output)")

    # Error if present
    error = cell.get_error()
    if error:
        parts.append(f"\n\n## Error\n\n```\n{error}\n```")

    # Algorithm step context
    if algorithm_step:
        parts.append(f"\n\n## Expected (from algorithm)\n\n")
        parts.append(f"**Description**: {algorithm_step.description}")
        if algorithm_step.expected_output:
            parts.append(f"\n**Expected Output**: {algorithm_step.expected_output}")
        if algorithm_step.validation_criteria:
            parts.append(f"\n**Validation Criteria**: {algorithm_step.validation_criteria}")

    # Additional context
    if context:
        parts.append(f"\n\n## Additional Context\n\n{context}")

    # Check for images
    if cell.has_images():
        parts.append("\n\n## Note\n\nThis cell generated image output (plot/visualization).")

    parts.append("\n\n## Your Task\n\nEvaluate this cell and respond with JSON only.")

    return "\n".join(parts)


async def evaluate_cell(
    model_router: ModelRouter,
    model_identifier: str,
    cell: Cell,
    algorithm_step: Optional[AlgorithmStep] = None,
    context: Optional[str] = None,
) -> Optional[SupervisorEvaluation]:
    """
    Evaluate a cell's execution result.

    Args:
        model_router: Router for LLM calls
        model_identifier: Model to use
        cell: The cell to evaluate
        algorithm_step: Optional algorithm step for context
        context: Additional context for evaluation

    Returns:
        SupervisorEvaluation or None if evaluation failed
    """
    # Skip markdown cells
    if cell.cell_type == "markdown":
        return SupervisorEvaluation(
            cell_id=cell.id,
            score=100,
            is_acceptable=True,
            correctness="Markdown cell - no execution needed",
            completeness="N/A",
            data_quality="N/A"
        )

    # Skip cells with errors - they clearly need retry
    if cell.status == "error":
        error_msg = cell.get_error() or "Unknown error"
        return SupervisorEvaluation(
            cell_id=cell.id,
            score=0,
            is_acceptable=False,
            correctness=f"Cell failed with error: {error_msg}",
            completeness="Not completed due to error",
            data_quality="N/A",
            issues=[error_msg],
            suggestions=["Fix the error and re-execute"],
            should_retry=True
        )

    # Build evaluation prompt
    user_prompt = build_evaluation_prompt(cell, algorithm_step, context)

    messages = [
        {"role": "system", "content": SUPERVISOR_SYSTEM_PROMPT},
        {"role": "user", "content": user_prompt}
    ]

    try:
        # Make a non-streaming call for evaluation
        full_response = ""

        async for chunk in model_router.chat_stream(
            model_identifier=model_identifier,
            messages=messages,
            tools=None,  # No tools for evaluation
            think=False
        ):
            try:
                data = json.loads(chunk)
                if "message" in data and "content" in data["message"]:
                    full_response += data["message"]["content"]
            except json.JSONDecodeError:
                pass

        # Parse the evaluation JSON
        evaluation = parse_evaluation_response(full_response, cell.id)

        if evaluation:
            logger.info(f"Cell {cell.id[:8]} evaluated: score={evaluation.score}, acceptable={evaluation.is_acceptable}")
        else:
            logger.warning("Failed to parse evaluation from response")

        return evaluation

    except Exception as e:
        logger.error(f"Cell evaluation failed: {e}")
        return None


def parse_evaluation_response(response: str, cell_id: str) -> Optional[SupervisorEvaluation]:
    """
    Parse the LLM response into a SupervisorEvaluation object.

    Handles various response formats.
    """
    # Try direct parsing
    try:
        data = json.loads(response.strip())
        data["cell_id"] = cell_id
        return SupervisorEvaluation.from_dict(data)
    except json.JSONDecodeError:
        pass

    # Try extracting from markdown code block
    json_match = re.search(r'```(?:json)?\s*(\{[\s\S]*?\})\s*```', response)
    if json_match:
        try:
            data = json.loads(json_match.group(1))
            data["cell_id"] = cell_id
            return SupervisorEvaluation.from_dict(data)
        except json.JSONDecodeError:
            pass

    # Try finding JSON object anywhere in text
    json_match = re.search(r'\{[\s\S]*"score"[\s\S]*\}', response)
    if json_match:
        try:
            data = json.loads(json_match.group())
            data["cell_id"] = cell_id
            return SupervisorEvaluation.from_dict(data)
        except json.JSONDecodeError:
            pass

    logger.warning(f"Could not parse evaluation from response: {response[:500]}...")
    return None


def extract_images_from_cell(cell: Cell) -> List[Tuple[str, str]]:
    """
    Extract base64-encoded images from a cell's outputs.

    Returns:
        List of (mime_type, base64_data) tuples
    """
    images = []
    for output in cell.outputs:
        if output.data:
            for mime_type in ["image/png", "image/jpeg"]:
                if mime_type in output.data:
                    images.append((mime_type, output.data[mime_type]))
    return images


async def validate_plot_with_vision(
    model_router: ModelRouter,
    vision_model_identifier: str,
    image_data: str,
    mime_type: str = "image/png"
) -> Optional[Dict[str, Any]]:
    """
    Validate a plot using a vision model.

    Args:
        model_router: Router for LLM calls
        vision_model_identifier: Vision-capable model to use
        image_data: Base64-encoded image data
        mime_type: MIME type of the image

    Returns:
        Dict with validation results or None if validation failed
    """
    # Build vision message with image
    messages = [
        {
            "role": "user",
            "content": [
                {
                    "type": "image",
                    "source": {
                        "type": "base64",
                        "media_type": mime_type,
                        "data": image_data
                    }
                },
                {
                    "type": "text",
                    "text": VISION_PLOT_PROMPT
                }
            ]
        }
    ]

    try:
        full_response = ""

        async for chunk in model_router.chat_stream(
            model_identifier=vision_model_identifier,
            messages=messages,
            tools=None,
            think=False
        ):
            try:
                data = json.loads(chunk)
                if "message" in data and "content" in data["message"]:
                    full_response += data["message"]["content"]
            except json.JSONDecodeError:
                pass

        # Parse the vision response
        # Try direct JSON parse
        try:
            return json.loads(full_response.strip())
        except json.JSONDecodeError:
            pass

        # Try extracting from markdown code block
        json_match = re.search(r'```(?:json)?\s*(\{[\s\S]*?\})\s*```', full_response)
        if json_match:
            try:
                return json.loads(json_match.group(1))
            except json.JSONDecodeError:
                pass

        logger.warning(f"Could not parse vision response: {full_response[:500]}...")
        return None

    except Exception as e:
        logger.error(f"Vision validation failed: {e}")
        return None


class CoderSupervisor:
    """
    Supervisor that evaluates code cells and triggers retries.

    Tracks retry counts per cell and provides feedback to the coder agent.
    Includes optional vision-based validation for plot outputs.
    """

    def __init__(
        self,
        model_router: ModelRouter,
        model_identifier: str,
        max_retries: int = 3,
        vision_model_identifier: Optional[str] = None
    ):
        """
        Initialize the supervisor.

        Args:
            model_router: Router for LLM calls
            model_identifier: Model to use for evaluation
            max_retries: Maximum retries per cell before giving up
            vision_model_identifier: Vision-capable model for plot validation (optional)
        """
        self.model_router = model_router
        self.model_identifier = model_identifier
        self.max_retries = max_retries
        self.vision_model_identifier = vision_model_identifier
        self._retry_counts: Dict[str, int] = {}
        self._evaluations: List[SupervisorEvaluation] = []

    async def _validate_plots(self, cell: Cell) -> Optional[Dict[str, Any]]:
        """
        Validate plots in cell output using vision model.

        Returns combined validation result or None if no vision model configured.
        """
        if not self.vision_model_identifier:
            return None

        images = extract_images_from_cell(cell)
        if not images:
            return None

        # Validate the first image (typically there's only one plot per cell)
        mime_type, image_data = images[0]

        logger.info(f"Validating plot in cell {cell.id[:8]} using vision model")

        return await validate_plot_with_vision(
            model_router=self.model_router,
            vision_model_identifier=self.vision_model_identifier,
            image_data=image_data,
            mime_type=mime_type
        )

    async def evaluate(
        self,
        cell: Cell,
        algorithm_step: Optional[AlgorithmStep] = None,
        context: Optional[str] = None
    ) -> SupervisorEvaluation:
        """
        Evaluate a cell and determine if it needs retry.

        Includes vision-based validation for cells with plot outputs.

        Args:
            cell: The cell to evaluate
            algorithm_step: Optional algorithm step for context
            context: Additional context

        Returns:
            SupervisorEvaluation with quality assessment
        """
        evaluation = await evaluate_cell(
            model_router=self.model_router,
            model_identifier=self.model_identifier,
            cell=cell,
            algorithm_step=algorithm_step,
            context=context
        )

        if not evaluation:
            # Default to passing if evaluation fails
            evaluation = SupervisorEvaluation(
                cell_id=cell.id,
                score=60,
                is_acceptable=True,
                correctness="Evaluation unavailable - assuming acceptable",
                completeness="Unknown",
                data_quality="Unknown"
            )

        # Vision validation for cells with plots
        if cell.has_images() and self.vision_model_identifier:
            vision_result = await self._validate_plots(cell)

            if vision_result:
                evaluation.has_plot = True
                vision_score = vision_result.get("quality_score", 50)
                evaluation.plot_assessment = vision_result.get("summary", "")

                # Add vision issues to evaluation
                vision_issues = vision_result.get("issues", [])
                if vision_issues:
                    evaluation.issues.extend(vision_issues)

                # Check for empty/blank plots
                if not vision_result.get("has_data", True):
                    evaluation.issues.append("Plot appears to be empty or shows no data")
                    evaluation.score = min(evaluation.score, 20)
                    evaluation.is_acceptable = False
                    evaluation.suggestions.append("Ensure the plot is displaying actual data")

                # Adjust score based on vision quality
                # Weight: 70% code evaluation, 30% vision evaluation
                combined_score = int(0.7 * evaluation.score + 0.3 * vision_score)
                evaluation.score = combined_score
                evaluation.is_acceptable = combined_score >= 50

                logger.info(f"Vision validation: score={vision_score}, combined={combined_score}")

        # Check retry count
        current_retries = self._retry_counts.get(cell.id, 0)

        if not evaluation.is_acceptable and current_retries < self.max_retries:
            evaluation.should_retry = True
            self._retry_counts[cell.id] = current_retries + 1
            logger.info(f"Cell {cell.id[:8]} needs retry ({current_retries + 1}/{self.max_retries})")
        elif not evaluation.is_acceptable:
            evaluation.should_retry = False  # Max retries reached
            logger.warning(f"Cell {cell.id[:8]} failed after {self.max_retries} retries")

        self._evaluations.append(evaluation)
        return evaluation

    def get_retry_count(self, cell_id: str) -> int:
        """Get the current retry count for a cell."""
        return self._retry_counts.get(cell_id, 0)

    def reset_retry_count(self, cell_id: str) -> None:
        """Reset the retry count for a cell (e.g., after successful edit)."""
        self._retry_counts.pop(cell_id, None)

    def get_all_evaluations(self) -> List[SupervisorEvaluation]:
        """Get all evaluations performed by this supervisor."""
        return self._evaluations.copy()

    def get_summary(self) -> Dict[str, Any]:
        """Get a summary of all evaluations."""
        if not self._evaluations:
            return {"total": 0, "passed": 0, "failed": 0, "avg_score": 0}

        passed = sum(1 for e in self._evaluations if e.is_acceptable)
        scores = [e.score for e in self._evaluations]

        return {
            "total": len(self._evaluations),
            "passed": passed,
            "failed": len(self._evaluations) - passed,
            "avg_score": sum(scores) / len(scores) if scores else 0
        }
