"""
Data schemas for the Orchestrator system.

These dataclasses define the structure of plans, steps, and state
used throughout the orchestration process.

"""

from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
from enum import Enum
from datetime import datetime
import uuid
import json
import asyncio


class PlanStatus(Enum):
    """Status of the overall execution plan."""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    AWAITING_USER = "awaiting_user"


class StepStatus(Enum):
    """Status of individual plan steps."""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


@dataclass
class PlanStep:
    """
    A single step in the execution plan.

    Each step represents one tool call to be executed by a specific agent.
    """
    step_id: str                              # "step_1", "step_2", etc.
    description: str                          # Human-readable description
    agent_role: str                           # "handyman", "coder", "vision", "editor"
    tool_name: str                            # Specific tool to call
    tool_args: Dict[str, Any]                 # Arguments for the tool
    expected_output: str                      # What we expect to get back
    reasoning: str                            # Why this step is needed

    # Runtime fields (set during execution)
    status: StepStatus = StepStatus.PENDING
    result: Optional[str] = None              # Tool result
    error: Optional[str] = None               # Error message if failed
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    retry_count: int = 0                      # Number of retry attempts

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "step_id": self.step_id,
            "description": self.description,
            "agent_role": self.agent_role,
            "tool_name": self.tool_name,
            "tool_args": self.tool_args,
            "expected_output": self.expected_output,
            "reasoning": self.reasoning,
            "status": self.status.value,
            "result": self.result,
            "error": self.error,
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
            "retry_count": self.retry_count,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "PlanStep":
        """Create PlanStep from dictionary."""
        return cls(
            step_id=data["step_id"],
            description=data["description"],
            agent_role=data["agent_role"],
            tool_name=data["tool_name"],
            tool_args=data.get("tool_args", {}),
            expected_output=data.get("expected_output", ""),
            reasoning=data.get("reasoning", ""),
            status=StepStatus(data.get("status", "pending")),
            result=data.get("result"),
            error=data.get("error"),
            retry_count=data.get("retry_count", 0),
        )


@dataclass
class ExecutionPlan:
    """
    The complete execution plan generated by the orchestrator.

    Contains the goal, reasoning, and ordered list of steps to execute.
    """
    plan_id: str                              # UUID
    goal: str                                 # What we're trying to achieve
    steps: List[PlanStep]                     # Ordered steps to execute
    reasoning: str                            # Orchestrator's reasoning for this plan

    # Metadata
    status: PlanStatus = PlanStatus.PENDING
    created_at: datetime = field(default_factory=datetime.now)
    requires_confirmation: bool = False       # True if high-risk operations

    # Runtime tracking
    current_step_index: int = 0
    replan_count: int = 0                     # How many times we've replanned

    def current_step(self) -> Optional[PlanStep]:
        """Get the current step to execute."""
        if self.current_step_index < len(self.steps):
            return self.steps[self.current_step_index]
        return None

    def advance(self) -> bool:
        """Move to next step. Returns False if no more steps."""
        self.current_step_index += 1
        return self.current_step_index < len(self.steps)

    def is_complete(self) -> bool:
        """Check if all steps are done."""
        return self.current_step_index >= len(self.steps)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "plan_id": self.plan_id,
            "goal": self.goal,
            "steps": [s.to_dict() for s in self.steps],
            "reasoning": self.reasoning,
            "status": self.status.value,
            "created_at": self.created_at.isoformat(),
            "requires_confirmation": self.requires_confirmation,
            "current_step_index": self.current_step_index,
            "replan_count": self.replan_count,
        }

    def to_markdown(self) -> str:
        """Convert plan to human-readable markdown."""
        lines = [
            f"**Goal:** {self.goal}",
            "",
            "**Steps:**",
        ]
        for i, step in enumerate(self.steps, 1):
            status_icon = {
                StepStatus.PENDING: "⏳",
                StepStatus.IN_PROGRESS: "🔄",
                StepStatus.COMPLETED: "✅",
                StepStatus.FAILED: "❌",
                StepStatus.SKIPPED: "⏭️",
            }.get(step.status, "")
            lines.append(f"{i}. {status_icon} **{step.description}**")
            lines.append(f"   - Agent: `{step.agent_role}` → Tool: `{step.tool_name}`")
        return "\n".join(lines)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ExecutionPlan":
        """Create ExecutionPlan from dictionary (e.g., from LLM JSON output)."""
        steps = [PlanStep.from_dict(s) for s in data.get("steps", [])]
        return cls(
            plan_id=data.get("plan_id", str(uuid.uuid4())),
            goal=data.get("goal", ""),
            steps=steps,
            reasoning=data.get("reasoning", ""),
            status=PlanStatus(data.get("status", "pending")),
            requires_confirmation=data.get("requires_confirmation", False),
        )


@dataclass
class AnalysisResult:
    """
    Result of the query analysis phase (Phase 0).

    Determines whether to answer directly or create a plan.
    """
    decision: str                             # "direct_answer" or "needs_plan"
    reasoning: str                            # Why this decision was made
    complexity: str                           # "trivial", "simple", "moderate", "complex"
    thinking: str = ""                        # Full thinking content for audit trail

    @classmethod
    def from_dict(cls, data: Dict[str, Any], thinking: str = "") -> "AnalysisResult":
        """Create from LLM JSON output."""
        return cls(
            decision=data.get("decision", "needs_plan"),
            reasoning=data.get("reasoning", ""),
            complexity=data.get("complexity", "simple"),
            thinking=thinking,
        )


@dataclass
class ToolObservation:
    """
    Structured representation of a tool's output — P1-E-2 Context Engineering.

    Separates the compact context-window version (summary + key_findings) from
    the full raw output, which is preserved for UI display and audit trail but
    NOT injected into subsequent LLM context.

    Fields:
        summary: ≤400-word distilled version injected into the context window
        key_findings: Bullet points extracted from the observation
        citations: Source filenames / page numbers mentioned in the output
        confidence: Tool-reported confidence (0.0–1.0) if available
        raw_saved_to: Path or event key where the full raw output can be found
        raw_content: Full original tool output (not injected into context)
    """
    summary: str
    key_findings: List[str] = field(default_factory=list)
    citations: List[str] = field(default_factory=list)
    confidence: Optional[float] = None
    raw_saved_to: Optional[str] = None       # e.g. "tool_result event" or workspace path
    raw_content: Optional[str] = None

    def to_context_string(self) -> str:
        """Return the compact string to inject into the LLM context window."""
        parts = [self.summary]
        if self.key_findings:
            parts.append("\nKey findings:")
            parts.extend(f"  - {f}" for f in self.key_findings)
        if self.citations:
            parts.append("\nSources: " + "; ".join(self.citations))
        return "\n".join(parts)


@dataclass
class StepResult:
    """
    Result of executing a single plan step.

    Captures the tool output, agent thinking, and success status.

    Context engineering note (P1-E-2):
      `content` holds the distilled observation (≤2 000 chars) injected into
      subsequent LLM context.  `raw_content` holds the full original output
      for UI display only — it is NOT re-injected into context windows.
    """
    step_id: str
    success: bool
    content: str                              # Distilled tool result (context window)
    summary: str                              # Agent's summary of the result
    agent_thinking: str = ""                  # Agent's thinking during execution
    error: Optional[str] = None               # Error message if failed
    token_usage: Optional[Dict[str, int]] = None  # Token usage from tool
    raw_content: Optional[str] = None         # Full original tool output (UI only)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for storage."""
        return {
            "step_id": self.step_id,
            "success": self.success,
            "content": self.content,
            "summary": self.summary,
            "agent_thinking": self.agent_thinking,
            "error": self.error,
            "token_usage": self.token_usage,
            # raw_content intentionally omitted — not needed in serialized state
        }


@dataclass
class EvaluationResult:
    """
    Result of the orchestrator's evaluation of a step result.

    Determines whether to continue, retry, or fail.
    """
    success: bool                             # Did the step achieve its goal?
    summary: str                              # Brief summary of outcome
    should_continue: bool                     # Should we proceed to next step?
    reasoning: str                            # Why this decision was made
    issues: List[str] = field(default_factory=list)  # Any issues found
    thinking: str = ""                        # Full thinking for audit trail

    @classmethod
    def from_dict(cls, data: Dict[str, Any], thinking: str = "") -> "EvaluationResult":
        """Create from LLM JSON output."""
        return cls(
            success=data.get("success", False),
            summary=data.get("summary", ""),
            should_continue=data.get("should_continue", False),
            reasoning=data.get("reasoning", ""),
            issues=data.get("issues", []),
            thinking=thinking,
        )


@dataclass
class OrchestratorState:
    """
    Complete state of the orchestration process.

    This is the single source of truth for the entire execution.
    Tracks all phases, results, and history.
    """
    # Identity
    task_id: str
    user_query: str

    # Plan (set after planning phase)
    plan: Optional[ExecutionPlan] = None

    # Execution tracking
    phase: str = "analyzing"                  # "analyzing", "planning", "executing", "synthesizing", "complete", "error", "awaiting_user"
    step_results: List[Dict[str, Any]] = field(default_factory=list)

    # Context accumulation
    orchestrator_messages: List[Dict[str, str]] = field(default_factory=list)

    # Error recovery tracking
    consecutive_failures: int = 0
    max_failures: int = 3

    # User interaction
    pending_question: Optional[str] = None
    pending_collaboration: Optional[Dict[str, Any]] = None  # {tool, args, ...}
    collaboration_response: Optional[Any] = None

    # Final output
    final_answer: Optional[str] = None

    # Token tracking
    total_tokens: int = 0

    # Supervisor tracking (Phase 2A)
    steps_since_reflection: int = 0           # Steps completed since last reflection
    consecutive_low_quality: int = 0          # Consecutive steps with quality < threshold
    same_tool_streak: int = 0                 # Consecutive calls to same tool
    last_tool_name: Optional[str] = None      # Last tool called (for streak tracking)

    def add_step_result(self, result: StepResult) -> None:
        """Add a step result and track tokens."""
        self.step_results.append(result.to_dict())
        if result.token_usage:
            self.total_tokens += result.token_usage.get("total", 0)

    def get_step_result(self, step_id: str) -> Optional[Dict[str, Any]]:
        """Get a specific step result by ID."""
        for result in self.step_results:
            if result.get("step_id") == step_id:
                return result
        return None

    def to_dict(self) -> Dict[str, Any]:
        """Convert state to dictionary for debugging/logging."""
        return {
            "task_id": self.task_id,
            "user_query": self.user_query,
            "phase": self.phase,
            "plan": self.plan.to_dict() if self.plan else None,
            "step_results": self.step_results,
            "consecutive_failures": self.consecutive_failures,
            "pending_question": self.pending_question,
            "pending_collaboration": self.pending_collaboration,
            "final_answer_length": len(self.final_answer) if self.final_answer else 0,
            "total_tokens": self.total_tokens,
            "steps_since_reflection": self.steps_since_reflection,
            "consecutive_low_quality": self.consecutive_low_quality,
            "same_tool_streak": self.same_tool_streak,
        }


# =============================================================================
# Phase 2A: Supervisor Agent Schemas
# =============================================================================

@dataclass
class SupervisorEvaluation:
    """
    Result of the Supervisor Agent's quality evaluation of a step result.

    The Supervisor goes beyond pass/fail to assess:
    - Quality: Is this result actually useful?
    - Goal alignment: Does this advance us toward the objective?
    - Issues: What problems were identified?
    - Action: Should we retry, continue, or escalate?
    """
    quality_score: int                        # 0-100 quality assessment
    issues: List[str]                         # Problems identified
    suggestion: Optional[str]                 # Micro-adjustment suggestion if quality < threshold
    should_retry: bool                        # Should we retry this step?
    should_escalate: bool                     # Should we escalate to user? (Phase 2B)
    reasoning: str                            # Explanation for the user
    thinking: str = ""                        # Full thinking for audit trail

    # Quality thresholds
    QUALITY_THRESHOLD_GOOD: int = 70          # Above this = proceed
    QUALITY_THRESHOLD_ACCEPTABLE: int = 50    # Above this = maybe retry
    # Below ACCEPTABLE = definitely retry or escalate

    def is_good_quality(self) -> bool:
        """Check if quality is good enough to proceed without retry."""
        return self.quality_score >= self.QUALITY_THRESHOLD_GOOD

    def is_acceptable_quality(self) -> bool:
        """Check if quality is acceptable (might proceed with caveats)."""
        return self.quality_score >= self.QUALITY_THRESHOLD_ACCEPTABLE

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "quality_score": self.quality_score,
            "issues": self.issues,
            "suggestion": self.suggestion,
            "should_retry": self.should_retry,
            "should_escalate": self.should_escalate,
            "reasoning": self.reasoning,
            "thinking": self.thinking,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any], thinking: str = "") -> "SupervisorEvaluation":
        """Create from LLM JSON output."""
        return cls(
            quality_score=data.get("quality_score", 50),
            issues=data.get("issues", []),
            suggestion=data.get("suggestion"),
            should_retry=data.get("should_retry", False),
            should_escalate=data.get("should_escalate", False),
            reasoning=data.get("reasoning", ""),
            thinking=thinking,
        )


@dataclass
class MicroAdjustment:
    """
    A small adjustment to step parameters suggested by the Supervisor.

    Micro-adjustments are tried before escalating to full replan or user intervention.
    Examples:
    - Broaden/narrow search query
    - Try different index
    - Increase result limit
    - Change tool parameters
    """
    original_args: Dict[str, Any]             # Original tool arguments
    adjusted_args: Dict[str, Any]             # Adjusted tool arguments
    adjustment_reasoning: str                 # Why this adjustment might help
    attempt_number: int                       # Which retry attempt this is (1, 2, or 3)
    adjustment_type: str = "parameter_tweak"  # Type: "parameter_tweak", "query_broadening", "fallback_tool"

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "original_args": self.original_args,
            "adjusted_args": self.adjusted_args,
            "adjustment_reasoning": self.adjustment_reasoning,
            "attempt_number": self.attempt_number,
            "adjustment_type": self.adjustment_type,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "MicroAdjustment":
        """Create from LLM JSON output."""
        return cls(
            original_args=data.get("original_args", {}),
            adjusted_args=data.get("adjusted_args", {}),
            adjustment_reasoning=data.get("adjustment_reasoning", ""),
            attempt_number=data.get("attempt_number", 1),
            adjustment_type=data.get("adjustment_type", "parameter_tweak"),
        )


# =============================================================================
# Phase 2C: Collaboration Schemas
# =============================================================================

@dataclass
class CollaborationResponse:
    """
    Response from the user for a pending collaboration request.
    
    Used when the agent pauses execution to ask the user something,
    and the user responds via the UI.
    """
    response: Any                             # The actual response content
    tool_name: str                            # The tool that requested input
    task_id: str                              # The task ID
    action: Optional[str] = None              # "approve", "reject", "modify", "reply", "abort"
    modifications: Optional[Dict[str, Any]] = None  # If modifying a plan/step

    def to_dict(self) -> Dict[str, Any]:
        return {
            "response": self.response,
            "tool_name": self.tool_name,
            "task_id": self.task_id,
            "action": self.action,
            "modifications": self.modifications,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "CollaborationResponse":
        return cls(
            response=data.get("response"),
            tool_name=data.get("tool_name", ""),
            task_id=data.get("task_id", ""),
            action=data.get("action"),
            modifications=data.get("modifications"),
        )


@dataclass
class CollaborationContext:
    """
    Shared context for handling Human-in-the-Loop interactions.
    
    Passed from TaskManager to Orchestrator to allow pausing execution
    and waiting for user input without blocking the thread.
    """
    response_ready: asyncio.Event = field(default_factory=asyncio.Event)
    pending_response: Optional[CollaborationResponse] = None
    
    def reset(self):
        """Reset the context for the next interaction."""
        self.response_ready.clear()
        self.pending_response = None
